name: Build GitHub Page

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: 26.3

    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    
    - name: Test Emacs
      run: emacs --version
