name: Build GitHub Page

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: purcell/setup-emacs@master
      with:
        version: 26.3
    -
        name: Build
        run: emacs *.org --batch -f org-html-export-to-html && ls && mkdir build && mv *.html build/index.html
    -
        name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
