name: Build GitHub Page

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: purcell/setup-emacs@master
      with:
        version: 26.3
    -
        name: htmlize
        run: |
          curl -O https://raw.githubusercontent.com/hniksic/emacs-htmlize/master/htmlize.el
    -
        name: Build
        run: emacs *.org --batch -l htmlize.el -f org-html-export-to-html && ls && mkdir public && mv *.html public/index.html
    -
        name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
